service: serverless-boilerplate-database

custom:
  stage: ${opt:stage, self:provider.stage}
  region: sa-east-1
  MAIN_TABLE_NAME: ${self:custom.stage}-main

provider:
  name: aws
  runtime: nodejs14.x
  region: ${self:custom.region}

resources:
  Resources:
    MainTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: PK
            AttributeType: S
          -
            AttributeName: SK
            AttributeType: S
        KeySchema:
          -
            AttributeName: PK
            KeyType: HASH
          -
            AttributeName: SK
            KeyType: RANGE
        TableName: ${self:custom.MAIN_TABLE_NAME}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
  Outputs:
    MainTableArn:
      Value:
        Fn::GetAtt:
          - MainTable
          - Arn
      Export:
        Name: ${self:custom.stage}-MainTableArn
